Gizbet.WEB/Areas/Admin/Controllers/UsersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using AutoMapper;
using Gizbet.BLL.Interfaces;
using Gizbet.WEB.Models;
using PagedList;
using static Gizbet.WEB.Configuration.AutoMapperConfigurationWEB;

namespace Gizbet.WEB.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UsersController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUserService _userService;

        public UsersController(IUserService userService)
        {
            _userService = userService;
            _mapper = GetMapper();
        }

        public async Task<ActionResult> Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = page ?? 1;
            var users = _mapper.Map<List<ApplicationUserPublicModel>>(await _userService.GetAllAsync());
            return View(users.ToPagedList(pageNumber, pageSize));
        }

        public async Task<ActionResult> Ban(string userName)
        {
            await _userService.BanUserAsync(userName);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> UnBan(string userName)
        {
            await _userService.UnBanUserAsync(userName);
            return RedirectToAction("Index");
        }
    }
}

Gizbet.WEB/Controllers/CategoriesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Gizbet.BLL.Interfaces;
using Gizbet.WEB.Models;
using System.Threading.Tasks;
using AutoMapper;
using PagedList;
using static Gizbet.WEB.Configuration.AutoMapperConfigurationWEB;

namespace Gizbet.WEB.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ICategoryService _categoryService;

        public CategoriesController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
            _mapper = GetMapper();
        }

        [ChildActionOnly]
        public PartialViewResult CategoryList()
        {
            var res = Task.Run(() => _categoryService.GetAllAsync()).Result;
            var categories = _mapper.Map<List<CategoryModel>>(res);
            return PartialView("CategoryList", categories);
        }

        public async Task<ActionResult> Category(int id, int? page)
        {
            int pageSize = 6;
            int pageNumber = page ?? 1;
            var category = _mapper.Map<CategoryModel>(await _categoryService.GetAsync(id));
            ViewBag.CategoryName = category.Name;
            return View(category.Lots.Where(x=>!x.IsSold).ToPagedList(pageNumber, pageSize));
        }
    }
}

Gizbet.WEB/Controllers/LotsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using Gizbet.BLL.DTO;
using Gizbet.BLL.Interfaces;
using Gizbet.WEB.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using static Gizbet.WEB.Configuration.AutoMapperConfigurationWEB;

namespace Gizbet.WEB.Controllers
{
    [Authorize]
    public class LotsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ILotService _lotService;
        private readonly ICategoryService _categoryService;

        public LotsController(ILotService lotService,ICategoryService categoryService)
        {
            _lotService = lotService;
            _categoryService = categoryService;
            _mapper = GetMapper();
        }

        public async Task<ActionResult> Lot(int id)
        {
            var lotModel = _mapper.Map<LotPublicModel>(await _lotService.GetAsync(id));
            if (lotModel.IsSold)
                return View("LotSold", lotModel);
            return View(lotModel);
        }

        [HttpPost]
        public async Task<PartialViewResult> SearchResult(string request, int? page)
        {
            int pageSize = 6;
            int pageNumber = page ?? 1;
            request = request ?? "";
            var res = _mapper.Map<List<LotPublicModel>>(await _lotService.FindByAsync(x=>x.Name.Contains(request))); 
            return PartialView(res.Where(x=>!x.IsSold).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Search()
        {
            return View();
        }

        public async Task<ActionResult> Add()
        {
            ViewBag.Categories = _mapper.Map<List<CategoryModel>>(await _categoryService.GetAllAsync());
            return View();
        }

        public async Task<ActionResult> Reply(int id)
        {
            ViewBag.Categories = _mapper.Map<List<CategoryModel>>(await _categoryService.GetAllAsync());
            var lot = await _lotService.GetAsync(id);
            return View("Add", _mapper.Map<LotAddModel>(lot));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(LotAddModel lotModel)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = _mapper.Map<List<CategoryModel>>(await _categoryService.GetAllAsync());
                return View(lotModel);
            }

            string fileName = "no_photo.jpg";

            if (lotModel.UploadImage != null)
            {
                fileName = System.IO.Path.GetFileName(lotModel.UploadImage.FileName);
                lotModel.UploadImage.SaveAs(Server.MapPath("~/Content/Images/UserImages/" + fileName));
            }

            var lot = _mapper.Map<LotDTO>(lotModel);

            lot.OwnerId = int.Parse(User.Identity.GetUserId());
            lot.TimeOfPosting = DateTime.Now;
            lot.ImageName = fileName;

            await _lotService.AddAsync(lot);
            return View("SuccessLotAdd");
        }

        [HttpPost]
        public async Task<ActionResult> MakeBid(int lotId)
        {
            await _lotService.MakeBidAsync(lotId, int.Parse(User.Identity.GetUserId()));
            return RedirectToAction("Lot", new {id = lotId});
        }

        [HttpPost]
        public async Task<ActionResult> Buy(int lotId)
        {
            await _lotService.BuyLotAsync(lotId, int.Parse(User.Identity.GetUserId()));
            return RedirectToAction("Lot", new { id = lotId });
        }

        [HttpPost]
        public async Task<ActionResult> DeleteLot(int lotid)
        {
            await _lotService.DeleteLotByIdAsync(lotid);
            return View("SuccessLotRemove");
        }
    }
}

Gizbet.WEB/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gizbet</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                    <img src="~/Content/Images/main_ico.png" align="left" style="height: 32px; margin-top: -7px;" />
                    Gizbet
                </a>

            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Лоты", "Index", "Lots")</li>
                    <li>@Html.ActionLink("Категории", "Index", "Categories")</li>
                    <li>@Html.ActionLink("Пользователи", "Index", "Users")</li>
                    <li>@Html.ActionLink("На сайт", "Index", "Home", new { Area = "" }, null)</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a><span class="glyphicon glyphicon-user"></span> @User.Identity.Name</a></li>
                    <li><a href="@Url.Action("Logout", "Account", new {Area = ""})"><span class="glyphicon glyphicon-log-out"></span> Выход</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container">

    </div>

    <div class="container body-content">
        <div class="container">
            <div id="mainDiv" class="row">
                <div class="col-md-12">
                    @RenderBody()
                </div>
            </div>
        </div>

    </div>

    <footer id="footer">
        <h4 class="text-muted" align="right" style="margin: 15px; margin-right: 50px">&copy; @DateTime.Now.Year - Gizbet</h4>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", false)
</body>
</html>